# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 前端之路 - DRY
email: lizhenhua230@gmail.com
description: >
 记录前端之路的点点滴滴，不贪多，不急躁!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhenhua-lee.github.io" # the base hostname & protocol for your site
github_username:  zhenhua-lee
weibo: http://weibo.com/dry230
zhihu: http://www.zhihu.com/people/zhenhua.lee

permalink: none
# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
